name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  continuous-update:
    name: Continuous update
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: silver886/github-actions/checkout@master
      - name: Install Scoop
        run: |
          Invoke-WebRequest -UseBasicParsing https://get.scoop.sh -OutFile $env:TMP\scoop-install.ps1
          & "$env:TMP\scoop-install.ps1" -RunAsAdmin
      - name: Update manifests
        run: |
          $env:Path="~\scoop\shims;$env:Path"
          Get-ChildItem -Path .\bucket\ -Exclude $(
            Get-Content .\.scoopupdateignore |
            ForEach-Object {
              "$_.json"
            }
          ) |
          ForEach-Object {
            .\bin\checkver.ps1 $_.BaseName -u
          }
      - name: Create Pull Request
        uses: silver886/github-actions/create/pull-request@master
