name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  continuous-update:
    name: Continuous update
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $env:GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Scoop
        run: |
          Invoke-WebRequest -UseBasicParsing https://get.scoop.sh -OutFile $env:TMP\scoop-install.ps1
          & "$env:TMP\scoop-install.ps1" -RunAsAdmin
      - name: Update manifests
        run: |
          $env:Path="~\scoop\shims;$env:Path"
          Get-ChildItem -Path .\bucket\ -Exclude $(
            Get-Content .\.scoopupdateignore |
            ForEach-Object {
              "$_.json"
            }
          ) |
          ForEach-Object {
            .\bin\checkver.ps1 $_.BaseName -u
          }
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: continuous-update/${{steps.date.outputs.date}}
          branch-suffix: timestamp
          delete-branch: true
          commit-message: Update on ${{steps.date.outputs.date}}
          title: Continuous update on ${{steps.date.outputs.date}}
          body: |
            Auto-generated by `create-pull-request`[^1].

            [^1]: https://github.com/peter-evans/create-pull-request
          assignees: |
            silver886
          reviewers: |
            silver886
