name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  continuous-update:
    name: Continuous update
    runs-on: windows-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Scoop
        run: |
          Invoke-WebRequest -UseBasicParsing https://get.scoop.sh -OutFile $env:TMP\scoop-install.ps1
          & "$env:TMP\scoop-install.ps1" -RunAsAdmin
      - name: Update manifests
        run: |
          $env:Path="~\scoop\shims;$env:Path"
          Get-ChildItem -Path .\bucket\ -Exclude $(
            Get-Content .\.scoopupdateignore |
            ForEach-Object {
              "$_.json"
            }
          ) |
          ForEach-Object {
            .\bin\checkver.ps1 $_.BaseName -u
          }
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB}}
          commit-message: Update on ${{steps.date.outputs.date}}
          title: Continuous update on ${{steps.date.outputs.date}}
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: continuous-update/${{steps.date.outputs.date}}
          branch-suffix: timestamp
          delete-branch: true
          reviewers: silver886
